#----------------------------------------------------------------------
# CS415/515 Assignment 1
#----------------------------------------------------------------------

FLAGS = -std=c99 -pthread -g -DVERBOSE -Wall -Werror
CC=gcc

.PHONY: test
test: test.c
	$(CC) $(FLAGS) -o $@ test.c
