#!/bin/bash

#COMMANDS="qsort-omp prime-omp qsort-pthd"
SIZE=1000000
COM=$1
R="./$COM"
res=$COM"Results"

for y in 1 2 3 4; do
    SIZE=$(($SIZE*10))
    for x in 1 2 4 8 16 32 64 128; do
        echo "time ./$COM $SIZE $x"
        time $R $SIZE $x
    done
done
