#!/bin/bash

#COMMANDS="qsort qsort-omp prime prime-omp qsort-pthd"
SIZE=1000000
COM=$1
R="./$COM"
res=$COM"Results"

for y in 1 2 3 4; do
    SIZE=$(($SIZE*10))
    echo "time ./$COM $SIZE $x"
    time $R $SIZE $x
done
